### ISSUE TITLE
mitls.org is down

### ISSUE THREAD

**Issue by catalin-hritcu** [mitls/mitls-f7#1]

**Comment by beurdouche** [comment]
I've seen, but I have no way to access it ...  I'm emailing Alfredo and Pierre-Yves...

**Comment by catalin-hritcu** [comment]
It seems that now it works over http, but not over https

**Comment by catalin-hritcu** [comment]
Santiago says there is a certificate error, but I'm not even getting that

**Comment by ad-l** [comment]
The server on port 443 is not configured to send the intermediate certificate which causes an error if it isn't in cache.
